DROP TABLE IF EXISTS bands;
DROP TABLE IF EXISTS venues;


CREATE TABLE bands (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  genre VARCHAR(255),
  bio TEXT
);


CREATE TABLE venues (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  location VARCHAR(255)
);
